-- =====================================================================
-- Esquema Postgres para Supabase — Kite Addict Colombia (versión web)
--
-- QUÉ ES: el equivalente exacto del esquema SQLite de la app de escritorio
-- (migraciones 001–004 ya aplicadas), portado a Postgres.
--
-- CÓMO USARLO: en tu proyecto de Supabase abre "SQL Editor", pega TODO este
-- archivo y pulsa RUN. Es idempotente: puedes ejecutarlo dos veces sin romper.
--
-- Convenciones (heredadas del escritorio):
--   Dinero   -> bigint (pesos COP enteros, sin decimales)
--   Fechas   -> text ISO 'YYYY-MM-DD' (mismas cadenas que el escritorio)
--   Horas    -> bigint minutos desde medianoche (0..1439)
--   Boolean  -> integer 0/1 con CHECK (la app envía 0/1, no true/false)
--
-- Seguridad: RLS activado en todas las tablas; solo el rol `authenticated`
-- (el usuario cuyo password es el PIN) puede leer/escribir. `anon` no ve nada.
-- =====================================================================

-- ---------- Metadatos / configuración / trazabilidad de import ----------

create table if not exists settings (
  key         text primary key,
  value       jsonb,
  updated_at  text not null default to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
);

create table if not exists import_batches (
  id            bigint generated by default as identity primary key,
  source_file   text not null,
  source_sha256 text not null,
  status        text not null default 'running'
                check (status in ('running','completed','rolled_back','failed')),
  rows_ok       bigint not null default 0,
  rows_error    bigint not null default 0,
  started_at    text not null default to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
  finished_at   text
);

create table if not exists import_errors (
  id          bigint generated by default as identity primary key,
  batch_id    bigint not null references import_batches(id) on delete cascade,
  sheet       text not null,
  source_row  bigint,
  raw_json    text,
  reason      text,
  created_at  text not null default to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
);
create index if not exists ix_import_errors_batch on import_errors(batch_id);

-- ---------- Personas (una tabla con roles) ----------

create table if not exists persons (
  id                   bigint generated by default as identity primary key,
  full_name            text not null,
  name_normalized      text not null,
  nickname             text,
  nickname_normalized  text,

  is_client            integer not null default 0 check (is_client in (0,1)),
  is_professor         integer not null default 0 check (is_professor in (0,1)),
  is_supplier          integer not null default 0 check (is_supplier in (0,1)),

  passport             text,
  email                text,
  country              text,
  country_raw          text,
  birth_date           text,           -- ISO o NULL si irrecuperable
  birth_date_raw       text,
  check_in             text,
  check_out            text,
  garos                text,
  taking_course        integer default 0 check (taking_course in (0,1)),
  discount_pct         double precision default 0, -- porcentaje 0..100
  paid                 bigint default 0,
  still_here           integer default 1 check (still_here in (0,1)),
  comment              text,

  photo_path           text,
  photo_thumb_path     text,

  import_batch_id      bigint references import_batches(id),
  source_sheet         text,
  source_row           bigint,
  created_at           text not null default to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
  updated_at           text not null default to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
);
create index if not exists ix_persons_name_norm on persons(name_normalized);
create index if not exists ix_persons_nick_norm on persons(nickname_normalized);
create index if not exists ix_persons_roles     on persons(is_client, is_professor, is_supplier);
create unique index if not exists ux_persons_passport on persons(passport) where passport is not null and passport <> '';
create unique index if not exists ux_persons_email    on persons(email)    where email    is not null and email    <> '';

-- ---------- Catálogo de servicios y equipos ----------

create table if not exists service_catalog (
  id              bigint generated by default as identity primary key,
  name            text not null,
  name_normalized text not null,
  discipline      text,
  season_year     bigint,
  hours           double precision,
  days            double precision default 0, -- admite medios días (0.5)
  price           bigint,
  professor_pct   double precision default 0, -- fracción 0..1
  pay_model_json  text,                       -- ProfessorPayModel serializado
  is_class        integer not null default 0 check (is_class in (0,1)),
  active          integer not null default 1 check (active in (0,1)),
  import_batch_id bigint references import_batches(id),
  created_at      text not null default to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
);
create index if not exists ix_service_name_norm on service_catalog(name_normalized);

create table if not exists equipment (
  id              bigint generated by default as identity primary key,
  name            text not null,
  name_normalized text not null,
  category        text not null default 'kite'
                  check (category in ('kite','board','efoil','sup','wing','wake','other')),
  count           bigint default 1,
  price           bigint,
  active          integer not null default 1 check (active in (0,1)),
  import_batch_id bigint references import_batches(id)
);
create index if not exists ix_equipment_name_norm on equipment(name_normalized);

-- ---------- Transacciones / reservas (Club) ----------
-- Incluye ya la migración 002 (tx_type, check_in_at) y la 003 (professor_salary
-- con REDONDEO half-up). En SQLite eran GENERATED VIRTUAL; aquí son STORED
-- (mismo resultado; Postgres las materializa).
--   * CAST(x + 0.5 AS INTEGER) de SQLite trunca tras sumar 0.5 = redondeo
--     half-up para valores >= 0  ->  floor(x + 0.5)::bigint en Postgres.
--     (No usamos round(): sobre double hace redondeo "bancario".)

create table if not exists transactions (
  id                     bigint generated by default as identity primary key,
  tx_date                text not null,
  start_min              bigint,
  end_min                bigint,
  service_raw            text,
  service_id             bigint references service_catalog(id),
  is_class               integer default 0 check (is_class in (0,1)),
  resolved_service_id    bigint references service_catalog(id),
  professor_id           bigint references persons(id),
  client_id              bigint references persons(id),
  kite_id                bigint references equipment(id),
  board_id               bigint references equipment(id),
  price_snapshot         bigint,
  professor_pct_snapshot double precision,
  price_override         bigint,
  tx_type                text not null default 'service'
                         check (tx_type in ('class','loan','service','other')),
  check_in_at            text,
  price_effective        bigint generated always as (coalesce(price_override, price_snapshot)) stored,
  duration_min           bigint generated always as (
                           case when end_min is not null and start_min is not null
                                then end_min - start_min end) stored,
  professor_salary       bigint generated always as (
                           floor((coalesce(price_override, price_snapshot)::numeric
                                  * coalesce(professor_pct_snapshot, 0)::numeric) + 0.5)::bigint
                         ) stored,
  comment                text,
  import_batch_id        bigint references import_batches(id),
  source_sheet           text,
  source_row             bigint,
  created_at             text not null default to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
);
create index if not exists ix_tx_date      on transactions(tx_date);
create index if not exists ix_tx_professor on transactions(professor_id, tx_date);
create index if not exists ix_tx_client    on transactions(client_id, tx_date);
create index if not exists ix_tx_service   on transactions(service_id);

-- ---------- Bar: productos y ventas ----------

create table if not exists bar_products (
  id              bigint generated by default as identity primary key,
  name            text not null,
  name_normalized text not null,
  box_price       bigint,
  units_per_box   double precision,
  sell_price      bigint,
  active          integer not null default 1 check (active in (0,1)),
  import_batch_id bigint references import_batches(id)
);
create index if not exists ix_bar_products_norm on bar_products(name_normalized);

create table if not exists bar_sales (
  id              bigint generated by default as identity primary key,
  sale_date       text not null,
  client_id       bigint references persons(id),
  client_raw      text,
  product_id      bigint references bar_products(id),
  product_raw     text,
  qty             double precision default 1,
  total           bigint,
  paid_cash       integer default 0 check (paid_cash in (0,1)),
  already_paid    integer default 0 check (already_paid in (0,1)),
  import_batch_id bigint references import_batches(id),
  source_sheet    text,
  source_row      bigint
);
create index if not exists ix_bar_sales_date    on bar_sales(sale_date);
create index if not exists ix_bar_sales_product on bar_sales(product_id);

-- ---------- Gastos ----------

create table if not exists expenses (
  id              bigint generated by default as identity primary key,
  expense_date    text not null,
  supply_name     text,
  count           double precision default 1,
  area_name       text,
  area_person_id  bigint references persons(id),
  supplier_id     bigint references persons(id),
  supplier_raw    text,
  amount_out      bigint not null,
  comment         text,
  import_batch_id bigint references import_batches(id),
  source_sheet    text,
  source_row      bigint
);
create index if not exists ix_expenses_date     on expenses(expense_date);
create index if not exists ix_expenses_supplier on expenses(supplier_id);
create index if not exists ix_expenses_area     on expenses(area_person_id);

-- ---------- Facturas de cliente ----------

create table if not exists client_bills (
  id             bigint generated by default as identity primary key,
  client_id      bigint not null references persons(id),
  bill_date      text not null,
  lodging_days   bigint default 0,
  lodging_rate   bigint default 0,
  discount_pct   double precision default 0,
  deductions     bigint default 0,
  already_paid   bigint default 0,
  card_surcharge integer not null default 0 check (card_surcharge in (0,1)),
  subtotal       bigint,
  total          bigint,
  net_to_pay     bigint,
  status         text not null default 'draft' check (status in ('draft','issued','paid','void')),
  pdf_path       text,
  emailed_at     text,
  notes          text,
  created_at     text not null default to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
);
create index if not exists ix_bills_client on client_bills(client_id, bill_date);

create table if not exists client_bill_items (
  id             bigint generated by default as identity primary key,
  bill_id        bigint not null references client_bills(id) on delete cascade,
  kind           text not null check (kind in ('service','bar','lodging','deduction','other')),
  transaction_id bigint references transactions(id),
  bar_sale_id    bigint references bar_sales(id),
  description    text not null,
  qty            double precision default 1,
  unit_price     bigint,
  line_total     bigint
);
create index if not exists ix_bill_items_bill on client_bill_items(bill_id);

-- ---------- Liquidación de profesores ----------

create table if not exists professor_settlements (
  id                bigint generated by default as identity primary key,
  professor_id      bigint not null references persons(id),
  period_year       bigint not null,
  period_month      bigint not null check (period_month between 1 and 12),
  gross_salary      bigint,
  bar_discount      bigint default 0,
  expenses_assigned bigint default 0,
  net_amount        bigint,
  status            text not null default 'draft' check (status in ('draft','issued','paid')),
  pdf_path          text,
  emailed_at        text,
  created_at        text not null default to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'),
  unique (professor_id, period_year, period_month)
);

-- Abonos (pagos parciales) de la liquidación. Cada abono genera además un gasto
-- (expenses) a nombre del profesor; expense_id lo enlaza para poder borrarlo junto.
create table if not exists settlement_payments (
  id            bigint generated by default as identity primary key,
  professor_id  bigint not null references persons(id),
  period_year   bigint not null,
  period_month  bigint not null check (period_month between 1 and 12),
  pay_date      text not null,
  amount        bigint not null check (amount > 0),
  comment       text,
  expense_id    bigint references expenses(id),
  created_at    text not null default to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
);
create index if not exists ix_settlement_payments_period
  on settlement_payments(professor_id, period_year, period_month);

-- ---------- Planes de pago / amortización ----------

create table if not exists payment_plans (
  id              bigint generated by default as identity primary key,
  title           text not null,
  person_id       bigint references persons(id),
  equipment_id    bigint references equipment(id),
  principal       bigint not null,
  start_date      text,
  status          text not null default 'active' check (status in ('active','settled','cancelled')),
  import_batch_id bigint references import_batches(id),
  created_at      text not null default to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
);

create table if not exists payment_plan_installments (
  id        bigint generated by default as identity primary key,
  plan_id   bigint not null references payment_plans(id) on delete cascade,
  paid_date text not null,
  amount    bigint not null,
  comment   text
);
create index if not exists ix_installments_plan on payment_plan_installments(plan_id, paid_date);

-- ---------- Respuestas de Google Forms (Reservas Web) ----------

create table if not exists form_responses (
  id                 bigint generated by default as identity primary key,
  form_key           text not null,          -- clave del formulario configurado (settings google_forms)
  row_hash           text not null unique,   -- sha256 de la fila -> dedupe entre sincronizaciones
  submitted_at       text,                   -- Marca temporal del form (ISO), si se pudo parsear
  raw_json           text not null,          -- objeto { encabezado: valor } con la fila completa
  status             text not null default 'new' check (status in ('new','imported','ignored')),
  imported_person_id bigint references persons(id),
  imported_tx_id     bigint references transactions(id),
  created_at         text not null default to_char(now() at time zone 'utc', 'YYYY-MM-DD"T"HH24:MI:SS"Z"')
);
create index if not exists ix_form_responses_form   on form_responses(form_key, status);
create index if not exists ix_form_responses_status on form_responses(status);

-- ---------- Vista de edades (equivalente a v_person_ages de SQLite) ----------
-- security_invoker: la vista respeta el RLS del usuario que consulta.

create or replace view v_person_ages
with (security_invoker = true) as
select id, full_name,
       extract(year from age(current_date, birth_date::date))::bigint as age
from persons
where birth_date is not null
  and birth_date ~ '^\d{4}-\d{2}-\d{2}$'
  and birth_date::date <= current_date;

-- =====================================================================
-- RLS: todo privado; solo `authenticated` (el usuario del PIN) entra.
-- =====================================================================

do $$
declare t text;
begin
  foreach t in array array[
    'settings','import_batches','import_errors','persons','service_catalog',
    'equipment','transactions','bar_products','bar_sales','expenses',
    'client_bills','client_bill_items','professor_settlements','settlement_payments',
    'payment_plans','payment_plan_installments','form_responses'
  ] loop
    execute format('alter table %I enable row level security', t);
    execute format('drop policy if exists todo_authenticated on %I', t);
    execute format(
      'create policy todo_authenticated on %I for all to authenticated using (true) with check (true)', t
    );
  end loop;
end $$;

-- =====================================================================
-- Storage: buckets privados 'fotos' (personas) y 'archivos' (pestaña Archivos)
-- =====================================================================

insert into storage.buckets (id, name, public)
values ('fotos', 'fotos', false), ('archivos', 'archivos', false)
on conflict (id) do nothing;

drop policy if exists fotos_archivos_authenticated on storage.objects;
create policy fotos_archivos_authenticated on storage.objects
  for all to authenticated
  using (bucket_id in ('fotos', 'archivos'))
  with check (bucket_id in ('fotos', 'archivos'));

-- =====================================================================
-- NOTA sobre la carga inicial (seed): el script scripts/seed-supabase-run.cjs
-- inserta conservando los ids de origen. Tras ejecutarlo, pega en el SQL
-- Editor las sentencias setval(...) que el propio script imprime al final,
-- para que los ids nuevos sigan después de los importados.
-- =====================================================================
